<!doctype html>
<html lang="en">

<head>
    <title><?=isset($title) ? $title . ' - laserprofile' : 'laserprofile - Laser Tag Application';?></title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <link href="assets/index.css" rel="stylesheet" />
</head>

<body class="bg-dark">
